"""Create goals table

Revision ID: 1428f3f9a93d
Revises: 6afaf1651dfd
Create Date: 2024-09-19 20:06:15.800654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1428f3f9a93d'
down_revision: Union[str, None] = '6afaf1651dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'goal_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('goals', 'target_value',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workouts', 'workout_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workouts', 'calories',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'calories',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('workouts', 'workout_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('goals', 'target_value',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('goals', 'goal_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
